/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Project;
import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Task;
import util.ButtonColumnCellRenderer;
import util.DeadlineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author sidney
 */
public class MainScreen extends javax.swing.JFrame {
    
    ProjectController projectController;
    TaskController taskController;
    DefaultListModel projectListModel;
    TaskTableModel taskTableModel;
    
    public MainScreen() {
        initComponents();
        initControllers();
        initComponentsModel();
        
        decorateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_tasks = new javax.swing.JScrollPane();
        jTable_tasks = new javax.swing.JTable();
        jP_toobar = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        lb_subtitle = new javax.swing.JLabel();
        jP_projects = new javax.swing.JPanel();
        lb_project = new javax.swing.JLabel();
        lb_projectAdd = new javax.swing.JLabel();
        jP_tasks = new javax.swing.JPanel();
        lb_task = new javax.swing.JLabel();
        lb_taskAdd = new javax.swing.JLabel();
        jP_projectList = new javax.swing.JPanel();
        jSc_listProject = new javax.swing.JScrollPane();
        ListProject = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        EmptyList = new javax.swing.JPanel();
        lb_checkListTasksImage = new javax.swing.JLabel();
        lb_textNoTasks = new javax.swing.JLabel();
        lb_textInfo = new javax.swing.JLabel();

        jTable_tasks.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTable_tasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_tasks.setGridColor(java.awt.Color.white);
        jTable_tasks.setRowHeight(40);
        jTable_tasks.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jTable_tasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_tasks.setShowHorizontalLines(false);
        jTable_tasks.setShowVerticalLines(false);
        jTable_tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tasksMouseClicked(evt);
            }
        });
        jScrollPane_tasks.setViewportView(jTable_tasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 0));
        setMinimumSize(new java.awt.Dimension(550, 600));

        jP_toobar.setBackground(new java.awt.Color(255, 153, 0));

        lb_title.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lb_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lg.png"))); // NOI18N
        lb_title.setText("Task Manager");

        lb_subtitle.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lb_subtitle.setText("Anote tudo, não esqueça nada");

        javax.swing.GroupLayout jP_toobarLayout = new javax.swing.GroupLayout(jP_toobar);
        jP_toobar.setLayout(jP_toobarLayout);
        jP_toobarLayout.setHorizontalGroup(
            jP_toobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_toobarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_toobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_title)
                    .addComponent(lb_subtitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_toobarLayout.setVerticalGroup(
            jP_toobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_toobarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lb_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_subtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_projects.setBackground(java.awt.Color.white);
        jP_projects.setBorder(new javax.swing.border.MatteBorder(null));

        lb_project.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lb_project.setForeground(new java.awt.Color(255, 153, 0));
        lb_project.setText("Projetos");
        lb_project.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveProject(evt);
            }
        });

        lb_projectAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        lb_projectAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openProjectDialog(evt);
            }
        });

        javax.swing.GroupLayout jP_projectsLayout = new javax.swing.GroupLayout(jP_projects);
        jP_projects.setLayout(jP_projectsLayout);
        jP_projectsLayout.setHorizontalGroup(
            jP_projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_projectsLayout.createSequentialGroup()
                .addComponent(lb_project, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_projectAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_projectsLayout.setVerticalGroup(
            jP_projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_projectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_projectAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_tasks.setBackground(java.awt.Color.white);
        jP_tasks.setBorder(new javax.swing.border.MatteBorder(null));

        lb_task.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lb_task.setForeground(new java.awt.Color(255, 153, 0));
        lb_task.setText("Tarefas");

        lb_taskAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        lb_taskAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_taskAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_tasksLayout = new javax.swing.GroupLayout(jP_tasks);
        jP_tasks.setLayout(jP_tasksLayout);
        jP_tasksLayout.setHorizontalGroup(
            jP_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_tasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_task, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_taskAdd)
                .addContainerGap())
        );
        jP_tasksLayout.setVerticalGroup(
            jP_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_tasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_taskAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_projectList.setBackground(java.awt.Color.white);
        jP_projectList.setBorder(new javax.swing.border.MatteBorder(null));

        ListProject.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ListProject.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListProject.setSelectionBackground(new java.awt.Color(255, 153, 0));
        ListProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListProjectMouseClicked(evt);
            }
        });
        jSc_listProject.setViewportView(ListProject);

        javax.swing.GroupLayout jP_projectListLayout = new javax.swing.GroupLayout(jP_projectList);
        jP_projectList.setLayout(jP_projectListLayout);
        jP_projectListLayout.setHorizontalGroup(
            jP_projectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_projectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSc_listProject)
                .addContainerGap())
        );
        jP_projectListLayout.setVerticalGroup(
            jP_projectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_projectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSc_listProject))
        );

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.setLayout(new java.awt.BorderLayout());

        EmptyList.setBackground(java.awt.Color.white);

        lb_checkListTasksImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_checkListTasksImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LISTA.png"))); // NOI18N

        lb_textNoTasks.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lb_textNoTasks.setForeground(new java.awt.Color(255, 153, 0));
        lb_textNoTasks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_textNoTasks.setText("Nehuma tarefa por aqui :D");

        lb_textInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lb_textInfo.setForeground(new java.awt.Color(153, 153, 0));
        lb_textInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_textInfo.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout EmptyListLayout = new javax.swing.GroupLayout(EmptyList);
        EmptyList.setLayout(EmptyListLayout);
        EmptyListLayout.setHorizontalGroup(
            EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmptyListLayout.createSequentialGroup()
                .addGroup(EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_textInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addComponent(lb_textNoTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_checkListTasksImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        EmptyListLayout.setVerticalGroup(
            EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmptyListLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lb_checkListTasksImage)
                .addGap(18, 18, 18)
                .addComponent(lb_textNoTasks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_textInfo)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jPanel7.add(EmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_toobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jP_projectList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_projects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jP_tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_toobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_projectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveProject(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveProject

    }//GEN-LAST:event_saveProject

    private void openProjectDialog(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openProjectDialog
        ProjectDialogScreen dialog = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        
        dialog.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                loadProjects();
            }
        });
        

    }//GEN-LAST:event_openProjectDialog

    private void lb_taskAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_taskAddMouseClicked
        TaskDialogScreen taskDialog = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        
        Project project = (Project) projectListModel.get(ListProject.getSelectedIndex());
        taskDialog.setProject(project);
        
        taskDialog.setVisible(true);
        
        taskDialog.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                Project project = (Project) projectListModel.get(ListProject.getSelectedIndex());
                loadTasks(project.getId());
            }
        });
        

    }//GEN-LAST:event_lb_taskAddMouseClicked

    private void jTable_tasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tasksMouseClicked
        // TODO add your handling code here:

        int rowIndex = jTable_tasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTable_tasks.columnAtPoint(evt.getPoint());
        
        Task task = taskTableModel.getTasks().get(rowIndex);
        
        Project project = (Project) projectListModel.get(ListProject.getSelectedIndex());
        
        switch (columnIndex) {
            case 3:
                taskController.update(task);
                break;
            case 4:
                break;
            case 5:
                taskController.removeById(task.getId());
                taskTableModel.getTasks().remove(task);
                loadTasks(project.getId());
                break;
        }

    }//GEN-LAST:event_jTable_tasksMouseClicked

    private void ListProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListProjectMouseClicked
        
        int projectIndex = ListProject.getSelectedIndex();
        Project project = (Project) projectListModel.get(projectIndex);
        loadTasks(project.getId());

    }//GEN-LAST:event_ListProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmptyList;
    private javax.swing.JList<String> ListProject;
    private javax.swing.JPanel jP_projectList;
    private javax.swing.JPanel jP_projects;
    private javax.swing.JPanel jP_tasks;
    private javax.swing.JPanel jP_toobar;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jSc_listProject;
    private javax.swing.JScrollPane jScrollPane_tasks;
    private javax.swing.JTable jTable_tasks;
    private javax.swing.JLabel lb_checkListTasksImage;
    private javax.swing.JLabel lb_project;
    private javax.swing.JLabel lb_projectAdd;
    private javax.swing.JLabel lb_subtitle;
    private javax.swing.JLabel lb_task;
    private javax.swing.JLabel lb_taskAdd;
    private javax.swing.JLabel lb_textInfo;
    private javax.swing.JLabel lb_textNoTasks;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask() {
        jTable_tasks.getTableHeader().setFont(new Font("Segoe UI Black", Font.PLAIN, 14));
        jTable_tasks.getTableHeader().setBackground(new Color(255, 153, 0));
        jTable_tasks.setAutoCreateRowSorter(true);
        
        jTable_tasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRenderer());
        
        jTable_tasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("editTest2"));
        jTable_tasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("remove2"));
    }
    
    public void initControllers() {
        this.projectController = new ProjectController();
        this.taskController = new TaskController();
    }
    
    public void initComponentsModel() {
        projectListModel = new DefaultListModel();
        loadProjects();
        
        taskTableModel = new TaskTableModel();
        jTable_tasks.setModel(taskTableModel);
        
        if (!projectListModel.isEmpty()) {
            ListProject.setSelectedIndex(0);
            
            Project project = (Project) projectListModel.get(0);
            loadTasks(project.getId());
            
        }
    }
    
    public void loadTasks(int idProject) {
        List<Task> tasks = taskController.getAll(idProject);
        taskTableModel.setTasks(tasks);
        
        showTableTasks(!tasks.isEmpty());
    }
    
    public void loadProjects() {
        List<Project> projects = projectController.getAll();
        
        projectListModel.clear();
        
        for (int i = 0; i < projects.size(); i++) {
            Project project = new Project();
            project = projects.get(i);
            
            projectListModel.addElement(project);
        }
        
        ListProject.setModel(projectListModel);
        
    }
    
    private void showTableTasks(boolean hasTasks) {
        if (hasTasks) {
            //Existem tarefas

            if (EmptyList.isVisible()) {
                EmptyList.setVisible(false);
                jPanel7.remove(EmptyList);
            }
            
            jPanel7.add(jScrollPane_tasks);
            jScrollPane_tasks.setVisible(true);
            jScrollPane_tasks.setSize(jPanel7.getWidth(), jPanel7.getHeight());
            
        } else {
            if (jScrollPane_tasks.isVisible()) {
                jScrollPane_tasks.setVisible(false);
                jPanel7.remove(jScrollPane_tasks);
            }
            
            jPanel7.add(EmptyList);
            EmptyList.setVisible(true);
            EmptyList.setSize(jPanel7.getWidth(), jPanel7.getHeight());
        }
    }
    
}

